FROM registry.cn-shanghai.aliyuncs.com/choerodon-tools/javabase:0.8.2
COPY app.jar /knowledgebase-service.jar
COPY dist /dist
COPY enterpoint.sh /enterpoint.sh
RUN chmod 777 /enterpoint.sh
CMD /enterpoint.sh java $JAVA_OPTS $SKYWALKING_OPTS -jar /knowledgebase-service.jar
